### ISSUE TITLE
crash with sample from South Korea 

### ISSUE THREAD

**Issue by stax76** [VFR-maniac/L-SMASH-Works#48]
Hello,

I received a file from South Korea which crashes vslsmashsource.

`The link is deleted because of X-rated video`

ID : 1
Format : AVC
Format/Info : Advanced Video Codec
Format profile : High@L4.1
Format settings, CABAC : Yes
Format settings, ReFrames : 4 frames
Codec ID : V_MPEG4/ISO/AVC
Duration : 1mn 0s
Bit rate mode : Constant
Bit rate : 20.4 Mbps
Nominal bit rate : 23.0 Mbps
Width : 1 920 pixels
Height : 1 080 pixels
Display aspect ratio : 16:9
Frame rate mode : Variable
Frame rate : 59.940 (59940/1000) fps
Original frame rate : 29.970 (30000/1001) fps
Standard : NTSC
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 8 bits
Scan type : Interlaced
Scan type, store method : Separated fields
Scan order : Top Field First
Bits/(Pixel*Frame) : 0.164
Stream size : 148 MiB (100%)
Default : No
Forced : No
Color range : Limited
Color primaries : BT.709
Transfer characteristics : BT.709
Matrix coefficients : BT.709

**Comment by VFR-maniac** [comment]
Are you insane? Don't post X-rated videos on github issues.
There are developers who is under the age of 18.

**Comment by stax76** [comment]
topless girl here in Germany is probably legal for movies age 12...

**Comment by Sparktank** [comment]
Some countries and their states/provinces have a legal age of 21 for viewing pornographic content, and the definition varies from place to place. So while one country may view it as light enough for a per-pubscent child, other countries may find it criminal.
Github would likely favour international laws offended by the clip rather than listen to opinion.

**Comment by Sparktank** [comment]
https://help.github.com/articles/github-terms-of-service/#g-general-conditions
G. General Conditions, sub-section 7.
"We may, but have no obligation to, remove Content and Accounts containing Content that we determine in our sole discretion are unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party's intellectual property or these Terms of Service."

**Comment by VFR-maniac** [comment]
Fixed at 9828349b47a4bfac98f957f9bdb1e59830b4449a anyway.
